### ISSUE TITLE
Please stop using custom portage repo and use gentoo defaults

### ISSUE THREAD

**Issue by samip5** [sakaki-/gentoo-on-rpi-64bit#134]
Dear Sakaki,

I would kindly ask you to at least retain from using your own custom genpi64 repo, and use the gentoo default one (as primary) aswell document the masks you're doing as it's not really apparent till you try to install 12.x nodejs for example.

**Comment by sakaki-** [comment]
Hello @samip5,

I'm not quite sure what you're getting at here. The vast majority of packages on the image do come from `::gentoo` by default. However, without the custom `genpi64` overlay (or another like it), lots of things on the RPi3/4 wouldn't work correctly (as there would otherwise be e.g. missing setup files for WiFi, bluetooth etc. missing MMAL support, V4L2 support etc.)

Also, yes, a set of custom USE flags and masks are employed in the custom profile used on the image, as a vanilla Gentoo `arm64` build does not yet provide a full desktop experience (or indeed, for some packages, build at all). This is called out in the project's readme ([here](https://github.com/sakaki-/gentoo-on-rpi-64bit#profile)); the `genpi64` overlay readme also summarizes the main packages provided ([here](https://github.com/sakaki-/genpi64-overlay)) and the USE flags, masks etc. in the custom profile may be viewed [here](https://github.com/sakaki-/genpi64-overlay/tree/master/profiles/targets/rpi3). The custom settings are also necessary to ensure that the project's binhost is maximally useful for upgrades for new users (so that they don't have to compile things locally, unless deliberately going off-piste by adding new packages, or overriding USE flag defaults etc.)

You are of course welcome to switch to the default `arm64` profile, or override things locally (using `/etc/portage/package.unmask`, `/etc/portage/package.use` etc.), or to build up your own image from a stage3 / stage4, following e.g. Neddy's instructions ([here](https://wiki.gentoo.org/wiki/Raspberry_Pi_3_64_bit_Install)). But I will stick with using the overlay approach on this image for now; so closing.

Best, sakaki
