### ISSUE TITLE
Eeprom Image issue

### ISSUE THREAD

**Issue by devashish22** [sakaki-/gentoo-on-rpi-64bit#173]
I am getting below issue when installing EEPROM image.

`Install dev-embedded/rpi4-eeprom-images-7.2.1 into /var/tmp/portage/dev-embedded/rpi4-eeprom-images-7.2.1/image
Traceback (most recent call last):
  File "/usr/lib/portage/python3.6/doins.py", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib/portage/python3.6/doins.py", line 602, in main
    os.path.dirname(source)):
  File "/usr/lib/portage/python3.6/doins.py", line 450, in _doins
    return install_runner.install_file(source, os.path.dirname(dest))
  File "/usr/lib/portage/python3.6/doins.py", line 386, in install_file
    return self._ins_runner.run(source, dest_dir)
  File "/usr/lib/portage/python3.6/doins.py", line 195, in run
    sstat = os.stat(source)
FileNotFoundError: [Errno 2] No such file or directory: b'lib'
  ERROR: dev-embedded/rpi4-eeprom-images-7.2.1::genpi64 failed (install phase):
    doins failed`

**Comment by sakaki-** [comment]
Thanks @devashish22 for reporting this!

It appears that the upstream debs layouts have changed: as of v7.2.1, the `/lib/firmware/raspberrypi/bootloader/...` payload has moved from the `rpi-eeprom-images` to `rpi-eeprom` deb (look at the changes in size from v7.1.1 to v7.2.1 in [this directory](http://archive.raspberrypi.org/debian/pool/main/r/rpi-eeprom/)).

Should be fixed by the revbumps in https://github.com/sakaki-/genpi64-overlay/commit/8fc508f325c2e1e3e6b622c69d43e22568569035

Update again and hopefully the install will work successfully. If not then please re-open this issue.

Closing now.
